export const dataCard = [
	{
		"name": "Желудки утиные сушено-вяленые",
		"price": 550,
		"discount": 15,
		"wight": "100 г",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/1.jpg"
	},
	{
		"name": "Куриные желудочки для собак",
		"price": 450,
		"discount": 10,
		"wight": "100 г",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/2.jpg"
	},
	{
		"name": "Крупная говяжья сушено-вяленая жилка",
		"price": 360,
		"discount": 0,
		"wight": "100 г",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/3.jpg"
	},
	{
		"name": "Мелкая говяжья сушено-вяленая жилка",
		"price": 300,
		"discount": 0,
		"wight": "100 г",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/4.jpg"
	},
	{
		"name": "Калтык говяжий для собак",
		"price": 290,
		"discount": 0,
		"wight": "100 г",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/5.jpg"
	},
	{
		"name": "Бублик из бычьего корня",
		"price": 340,
		"discount": 0,
		"wight": "100 г",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/6.jpg"
	},
	{
		"name": "Копыто оленье",
		"price": 490,
		"discount": 0,
		"wight": "1 шт",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/7.jpg"
	},
	{
		"name": "Бараний рубец сушенный",
		"price": 330,
		"discount": 0,
		"wight": "100 г",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/8.jpg"
	},
	{
		"name": "Рубец говяжий для собак",
		"price": 290,
		"discount": 0,
		"wight": "100 г",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/9.jpg"
	},
	{
		"name": "Свиные уши для собак",
		"price": 330,
		"discount": 0,
		"wight": "100 г",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/10.jpg"
	},
	{
		"name": "Уши говяжьи для собак",
		"price": 330,
		"discount": 0,
		"wight": "100 г",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/11.jpg"
	},
	{
		"name": "Печенья с яблоком (печень говяжья, сердце)",
		"price": 340,
		"discount": 0,
		"wight": "14 шт",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/12.jpg"
	},
	{
		"name": "Рога оленя для собак весом до 3кг. Размер XS",
		"price": 350,
		"discount": 14,
		"wight": "1 шт",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/13.jpg"
	},
	{
		"name": "Рога оленя для собак весом от 3 до 5 кг. Размер S",
		"price": 400,
		"discount": 0,
		"wight": "1 шт",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/14.jpg"
	},
	{
		"name": "Рога оленя для собак весом от 5 до 10 кг. Размер M",
		"price": 600,
		"discount": 0,
		"wight": "1 шт",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/15.jpg"
	},
	{
		"name": "Рога оленя для собак весом от 10 до 30 кг. Размер L",
		"price": 800,
		"discount": 0,
		"wight": "1 шт",
		"description": "Описание demo",
		"isFavorite": false,
		"isCart": false,
		"available": true,
		"stock": 10,
		"picture": "https://react-learning.ru/image-compressed/16.jpg"
	},
	{
        "image": "http://dummyimage.com/400x200.png/5fa2dd/ffffff",
        "likes": [],
        "comments": [],
        "tags": [
            "legendary"
        ],
        "isPublished": true,
        "_id": "622bd9e806c7d323b8ae4615",
        "title": "Batman Beyond: Return of the Joker",
        "author": {
            "name": "Иван Иванов",
            "about": "Писатель",
            "avatar": "https://react-learning.ru/image-compressed/default-image.jpg",
            "_id": "622bd81b06c7d323b8ae4614",
            "email": "maxim_91@inbox.ru",
            "__v": 0
        },
        "text": "Change Other Device on Right Upper Arm",
        "created_at": "2022-03-11T23:23:20.891Z",
        "updated_at": "2022-03-11T23:23:20.891Z",
        "__v": 0
    },
]